tasks:
    - init: |
          pnpm install
      command: |
          clear &&
          echo "Welcome, they are my computer programming II homeworks." &&
          echo "I am Jacob Lin, a student at NTNU in Taiwan."
